# Gabriel Guimarães Vilas Boas Marin NUSP: 11218521
all: compile run

run: 
	./bin
compile:
	gcc -c queries.c main.c
	gcc -o bin  queries.o main.o
delete:
	rm bin alunos.dat index_primario.dat index_secundario.dat queries.o main.o lista_invertida.dat